### ISSUE TITLE
Plugin Croaks On <lastBuildDate> Tag

### ISSUE THREAD

**Issue by 24601** [logstash-plugins/logstash-input-rss#8]
For example, using the NYTimes feeds, it has errors like:

A plugin had an unrecoverable error. Will restart this plugin.
  Plugin: <LogStash::Inputs::Rss url=>"http://www.nytimes.com/services/xml/rss/nyt/MostViewed.xml">
  Error: undefined method `items' for nil:NilClass {:level=>:error}
A plugin had an unrecoverable error. Will restart this plugin.
  Plugin: <LogStash::Inputs::Rss url=>"http://www.nytimes.com/services/xml/rss/nyt/HomePage.xml">
  Error: undefined method `items' for nil:NilClass {:level=>:error}
A plugin had an unrecoverable error. Will restart this plugin.
  Plugin: <LogStash::Inputs::Rss url=>"http://www.nytimes.com/services/xml/rss/nyt/MostShared.xml">
  Error: undefined method `items' for nil:NilClass {:level=>:error}
A plugin had an unrecoverable error. Will restart this plugin.
  Plugin: <LogStash::Inputs::Rss url=>"http://topics.nytimes.com/top/opinion/editorialsandoped/editorials/index.html?rss=1">
  Error: value <Wed 17 Jun 2015 00:22:08 -0400> of tag <lastBuildDate> is not available. {:level=>:error}
A plugin had an unrecoverable error. Will restart this plugin.
  Plugin: <LogStash::Inputs::Rss url=>"http://topics.nytimes.com/top/opinion/editorialsandoped/oped/contributors/index.html?rss=1">
  Error: value <Wed 17 Jun 2015 00:22:08 -0400> of tag <lastBuildDate> is not available. {:level=>:error}

**Comment by brewcore** [comment]
I am also seeing this error, looks like it could be coming from the jruby rss parser.  In my case the field is 'pubDate'.  Here is the output from ```--debug```

Error: value <> of tag <pubDate> is not available.
  Exception: RSS::NotAvailableValueError
  Stack: logstash-1.5.4/vendor/jruby/lib/ruby/1.9/rss/0.9.rb:107:in `pubDate='

**Comment by itatabitovski** [comment]
I am trying the plugin for the first time. I tried with logstash 1.5.5 also without sucess, the output below is from logstash 2.0.0

```
A plugin had an unrecoverable error. Will restart this plugin.
  Plugin: <LogStash::Inputs::Rss interval=>15, url=>"https://rpm.newrelic.com/account_feeds/*********/events", codec=><LogStash::Codecs::Plain charset=>"UTF-8">>
  Error: value <Nov 11, '15  6:30 am> of tag <lastBuildDate> is not available.
  Exception: RSS::NotAvailableValueError
  Stack: /opt/logstash/vendor/jruby/lib/ruby/1.9/rss/0.9.rb:107:in `lastBuildDate='
/opt/logstash/vendor/jruby/lib/ruby/1.9/rss/parser.rb:456:in `start_get_text_element'
org/jruby/RubyProc.java:271:in `call'
/opt/logstash/vendor/jruby/lib/ruby/1.9/rss/parser.rb:358:in `tag_end'
/opt/logstash/vendor/jruby/lib/ruby/1.9/rexml/parsers/streamparser.rb:26:in `parse'
/opt/logstash/vendor/jruby/lib/ruby/1.9/rexml/document.rb:205:in `parse_stream'
/opt/logstash/vendor/jruby/lib/ruby/1.9/rss/rexmlparser.rb:22:in `_parse'
/opt/logstash/vendor/jruby/lib/ruby/1.9/rss/parser.rb:164:in `parse'
/opt/logstash/vendor/jruby/lib/ruby/1.9/rss/parser.rb:79:in `parse'
/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-rss-2.0.2/lib/logstash/inputs/rss.rb:66:in `handle_response'
/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-rss-2.0.2/lib/logstash/inputs/rss.rb:43:in `run'
/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.0.0-java/lib/logstash/pipeline.rb:180:in `inputworker'
/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.0.0-java/lib/logstash/pipeline.rb:174:in `start_input' {:level=>:error, :file=>"logstash/pipeline.rb", :line=>"192", :method=>"inputworker"}
```
